In [1]:
import pandas as pd

# Vectorizers and NLP Models
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation

In [2]:
df = pd.read_csv("/Users/nineve/code/emma-carballal/deepdj/raw_data/tcc_ceds_music_cleaned.csv", index_col=False)
df.head()

,Unnamed: 0,artist_name,track_name,genre,lyrics
0,0,mukesh,mohabbat bhi jhoothi,pop,hold time feel break feel untrue convince spea...
1,1,frankie laine,i believe,pop,believe drop rain fall grow believe darkest ni...
2,2,johnnie ray,cry,pop,sweetheart send letter goodbye secret feel bet...
3,3,pérez prado,patricia,pop,kiss lips want stroll charm mambo chacha merin...
4,4,giorgos papadopoulos,apopse eida oneiro,pop,till darling till matter know till dream live ...

In [3]:
vectorizer = TfidfVectorizer(max_df = 0.75, max_features = 5000, ngram_range=(1,2))
vectorized_songs = pd.DataFrame(vectorizer.fit_transform(df["lyrics"]).toarray(),
                                 columns = vectorizer.get_feature_names_out())

print(f" vectorized_songs.shape = {vectorized_songs.shape}")

 vectorized_songs.shape = (28372, 5000)

In [4]:
vectorized_songs

,aaah,abandon,able,absolutely,abuse,accept,account,accuse,accustom,ache,...,youre,youth,youths,zero,zing,zinga,zion,zombie,zone,zoom
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28367,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28368,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28369,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28370,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28371,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
text = "distinctly I remember it was in the bleak December"
vectorized_prompt = pd.DataFrame(vectorizer.transform([text]).toarray())
vectorized_prompt

,0,1,2,3,4,5,6,7,8,9,...,4990,4991,4992,4993,4994,4995,4996,4997,4998,4999
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
from scipy.spatial import distance

df["distance"] = [distance.cosine(vectorized_songs.iloc[k], vectorized_prompt) for k in range(len(vectorized_songs))]

In [14]:
closest = df["distance"].nsmallest(20)
indexes = closest.index

In [16]:
for idx in indexes:
    print(df[["artist_name", "track_name"]].iloc[idx])

artist_name     julie london
track_name     warm december
Name: 17336, dtype: object
artist_name    andy williams
track_name          remember
Name: 998, dtype: object
artist_name    the kingston trio
track_name       try to remember
Name: 23625, dtype: object
artist_name    edie brickell & new bohemians
track_name                   air of december
Name: 3447, dtype: object
artist_name            dean martin
track_name     don't you remember?
Name: 17255, dtype: object
artist_name    the brothers four
track_name       try to remember
Name: 940, dtype: object
artist_name    willie nelson
track_name      december day
Name: 8196, dtype: object
artist_name       coldplay
track_name     violet hill
Name: 5711, dtype: object
artist_name                    glen campbell
track_name     cold december (in your heart)
Name: 8022, dtype: object
artist_name    ella fitzgerald
track_name            remember
Name: 12746, dtype: object
artist_name    collective soul
track_name            december
Name: 4307, dtype: object
artist_name         perry como
track_name     try to remember
Name: 17836, dtype: object
artist_name        yo la tengo
track_name     our way to fall
Name: 4807, dtype: object
artist_name                             journey
track_name     remember me (feat. steve augeri)
Name: 25806, dtype: object
artist_name          hank williams
track_name     jesus remembered me
Name: 7130, dtype: object
artist_name                   the shangri-las
track_name     remember (walkin' in the sand)
Name: 4367, dtype: object
artist_name            faith evans
track_name     you used to love me
Name: 4309, dtype: object
artist_name            donna summer
track_name     i remember yesterday
Name: 2159, dtype: object
artist_name            tony bennett
track_name     when joanna loved me
Name: 17667, dtype: object
artist_name           harry nilsson
track_name     remember (christmas)
Name: 1635, dtype: object